import Head from "next/head";
import { Inter } from "@next/font/google";
import styled from "@emotion/styled";
import NavBar from "../components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title> ShopIT - OwnIT </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
    </>
  );
}

const Title = styled.title`
  color: red;
`;
